name: Commit

on:
  pull_request:
    branches: [main,master]
  workflow_call:
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Fetch commit-lint configuration
        run: wget https://raw.githubusercontent.com/vladdoster/.github/master/.commitlintrc
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: '.commitlintrc'
