name: Lint

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  commit:
    uses: vladdoster/.github/.github/workflows/commit.yml@master
  lint:
    uses: vladdoster/.github/.github/workflows/lint.yml@master
