name: Metrics
on:

  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          config_timezone: America/New_York

      - uses: lowlighter/metrics@latest
        with:
            filename: metrics/metrics.plugin.topics.icons.svg
            token: NOT_NEEDED
            base: ""
            plugin_topics: yes
            plugin_topics_limit: 0
            plugin_topics_mode: icons

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.plugin.lines.svg
          token: ${{ secrets.GH_TOKEN }}
          base: repositories
          plugin_lines: yes

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.plugin.topics.icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.plugin.stars.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 3

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.plugin.habits.facts.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          config_timezone: America/New_York


# Contributions by Category
# https://github.com/TheBoatyMcBoatFace/metrics/blob/main/source/plugins/contributors/README.md#plugin_contributors_categories
        name: Contributors by categories
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.plugin.contributors.categories.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          template: repository
          repo: metrics
          plugin_contributors: yes
          plugin_contributors_sections: categories
          plugin_contributors_categories: |
            {
              "Plugins & Templates":["source/plugins/**", "source/templates/**"],
              "Documentation":["README.md", "**/README.md", "**/metadata.yml"],
              "Code":["source/**", "Dockerfile"]
            }

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.plugin.starlists.svg
          token: NOT_NEEDED
          base: ""
          plugin_starlists: yes
          plugin_starlists_limit_repositories: 2
          plugin_starlists_only: TC39

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.plugin.notable.svg
          token: ${{ secrets.GH_TOKEN }}
          base: "metrics"
          plugin_notable: yes

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.base.svg
          token: ${{ secrets.GH_TOKEN }}
          base: header, activity, community, repositories, metadat
