name: Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    environment: 
      name: develop
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Fetch dependencies
        run: npm install --no-package-lock @semantic-release{/{'changelog','git','exec'},'-plus/docker'} @google/semantic-release-replace-plugin
      
      - name: Fetch semantic-release configuration
        run: wget https://raw.githubusercontent.com/vladdoster/.github/master/.releaserc.json
        
      - name: Generate release
        run: npx semantic-release --dry-run --repository ${{ github.repositoryUrl }} --ci --
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_EMAIL: 'mvdoster@gmail.com'
          GIT_AUTHOR_NAME: 'Vladislav Doster'
          GIT_COMMITTER_EMAIL: 'mvdoster@gmail.com'
          GIT_COMMITTER_NAME: 'Vladislav Doster'
